const languages = [
  { id: 1, name: "العربية" },
  { id: 2, name: "Български" },
  { id: 3, name: "Čeština" },
  { id: 4, name: "Dansk" },
  { id: 5, name: "Deutsch" },
  { id: 6, name: "Ελληνικά" },
  { id: 7, name: "English" },
  { id: 8, name: "Español" },
  { id: 9, name: "Eesti (Eesti)" },
  { id: 10, name: "Suomi" },
  { id: 11, name: "Français" },
  { id: 12, name: "עברית" },
  { id: 13, name: "Hrvatski" },
  { id: 14, name: "Magyar" },
  { id: 15, name: "Bahasa Indonesia" },
  { id: 16, name: "Italiano" },
  { id: 17, name: "日本語" },
  { id: 18, name: "한국어" },
  { id: 19, name: "Lietuvių (Lietuva)" },
  { id: 20, name: "‪Norsk Bokmål‬" },
  { id: 21, name: "Nederlands" },
  { id: 22, name: "Polski" },
  { id: 23, name: "Português" },
  { id: 24, name: "Português (Brasil)" },
  { id: 25, name: "Русский" },
  { id: 26, name: "Slovenčina" },
  { id: 27, name: "Српски" },
  { id: 28, name: "Svenska" },
  { id: 29, name: "ไทย" },
  { id: 30, name: "Türkçe" },
  { id: 31, name: "Українська" },
  { id: 32, name: "Tiếng Việt" },
  { id: 33, name: "简体中文" },
  { id: 34, name: "繁體中文" },
];

export default languages;
